-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.15.0
    hooks:
    -   id: pylint
